name: Telegram Bot (polling)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */5 * * *"

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 355
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          WELCOME_IMAGE: ${{ vars.WELCOME_IMAGE }}
          WEBAPP_URL: ${{ vars.WEBAPP_URL }}
          LINK_PRINCIPAL: ${{ vars.LINK_PRINCIPAL }}
          LINK_SECOURS: ${{ vars.LINK_SECOURS }}
          LINK_FEEDBACK: ${{ vars.LINK_FEEDBACK }}
          INFO_IMAGE: ${{ vars.INFO_IMAGE }}
        run: |
          python bot.py
