name: Telegram Bot

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"  # toutes les 6h

concurrency:
  group: telegram-bot
  cancel-in-progress: true

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 350  # < 6h
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot (polling)
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          WEBAPP_URL: ${{ vars.WEBAPP_URL }}
          WELCOME_IMAGE: ${{ vars.WELCOME_IMAGE }}
          INFO_IMAGE: ${{ vars.INFO_IMAGE }}
          LINK_PRINCIPAL: ${{ vars.LINK_PRINCIPAL }}
          LINK_SECOURS: ${{ vars.LINK_SECOURS }}
          LINK_FEEDBACK: ${{ vars.LINK_FEEDBACK }}
        run: |
          python bot.py